version: '3.4'

services:
  frontend:
    build: 
      dockerfile: ./docker/frontend/Dockerfile
      context: ./

  # nginx:
  #   build: ./docker/nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: always 
  #   volumes:
  #     - ./nginx/conf/:/etc/nginx/conf.d/:ro
  #     - ./certbot/www:/var/www/certbot/:ro

  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: frontend:3000
      SERVERNAME: anderscapital.eu
      EXTRANAMES: www.anderscapital.eu
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"
